camunda:
  bpm:
    admin-user:
      id: admin
      password: 123456
      first-name: admin
    filter:
      create: All tasks
#    dmn:
#      file-path: dmn/approve-decision.dmn

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda_engine?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
